# Lagrange Python (OneBot V11) Configuration

# 基本设置

uin: ""
# Bot QQ号 使用扫码登录

protocol: ""
# 登录协议 推荐使用Linux（默认）

sign_server: ""
# SignServer 地址 不可使用`Android`的`QSign`

######################################

# 通信方式，设置为空则代表不启用

reserved_ws_url: ""
# OneBot 反向 WebSocket 地址

forward_ws_host: ""
# OneBot 正向 WebSocket 监听地址

forward_ws_port: ""
# OneBot 正向 WebSocket 监听端口

http_post_url: ""
# OneBot HTTP POST 地址

http_get_host: ""
# OneBot HTTP GET API 监听地址

http_get_port: ""
# OneBot HTTP GET API 监听端口

#######################################

# 额外设置

log_level: "INFO"
# 日志等级

v6: True
# 是否启用IPv6

ignore_self: True
# 群消息是否忽略自身消息