# Lagrange Python (OneBot V11) Configuration

uin: ""
# Bot QQ号 使用扫码登录

protocol: ""
# 登录协议 推荐使用Linux（默认）

sign_server: ""
# SignServer 地址 不可使用`Android`的`QSign`

ws_url: ""
# OneBot 反向 WebSocket 地址

http_host: ""
# OneBot HTTP API 监听地址

http_port: ""
# OneBot HTTP API 监听端口

log_level: "INFO"
# 日志等级

v6: True
# 是否启用IPv6

ignore_self: True
# 群消息是否忽略自身消息